version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra
    restart: always
    environment:
      CASSANDRA_USER: cassandra_user
      CASSANDRA_PASSWORD: cassandra_password
      CASSANDRA_KEYSPACE: your_keyspace
    ports:
      - "9042:9042"

